SELECT COUNT(*) FROM H_JUAL_TEST HJT, PAY_JUAL_TEST pjt
WHERE HJT.LOKASI='A06'
AND HJT.NOBUKTI = pjt.NOBUKTI
AND HJT.TGL > TO_DATE('09/06/2018','MM/DD/YYYY')
AND HJT.TGL < TO_DATE('09/10/2018','MM/DD/YYYY')


AND EXISTS (SELECT * FROM h_JUAL HJ, PAY_JUAL pj
WHERE HJ.LOKASI='A06'
AND HJ.NOBUKTI = pj.NOBUKTI
AND HJ.TGL > TO_DATE('09/06/2018','MM/DD/YYYY'))

SELECT count(*) FROM d_JUAL_TEST HJT
WHERE HJT.LOKASI='A06'
AND HJT.TGL > TO_DATE('09/06/2018','MM/DD/YYYY')
AND HJT.TGL < TO_DATE('09/10/2018','MM/DD/YYYY')

AND EXISTS (SELECT * FROM D_JUAL HJ
WHERE HJ.LOKASI='A06'
AND HJ.TGL > TO_DATE('09/06/2018','MM/DD/YYYY'))

SELECT COUNT(*) FROM h_JUAL HJT, PAY_JUAL pjt
WHERE LOKASI='A06'
AND HJT.NOBUKTI = pjt.NOBUKTI
AND HJT.TGL > TO_DATE('09/06/2018','MM/DD/YYYY');
AND HJT.TGL < TO_DATE('09/10/2018','MM/DD/YYYY')

SELECT COUNT(*) FROM D_JUAL_TEST
WHERE LOKASI='A06'
AND TGL >= TO_DATE('09/06/2018','MM/DD/YYYY')
AND TGL <= TO_DATE('09/9/2018','MM/DD/YYYY')

SELECT COUNT(*) FROM D_JUAL dj
WHERE LOKASI='A06'
AND TGL >= TO_DATE('09/06/2018','MM/DD/YYYY')
AND TGL <= TO_DATE('09/9/2018','MM/DD/YYYY')



SELECT * FROM D_JUAL_TEST;

SELECT * FROM pay_jual_test;

truncate table H_JUAL_TEST;

truncate table D_JUAL_TEST;

TRUNCATE TABLE PAY_JUAL_TEST;

CREATE table D_JUAL_TEST as SELECT * from D_JUAL;

CREATE table PAY_JUAL_TEST as SELECT * from PAY_JUAL;
